---
- name: Setup my computing environment
  hosts: localhost
  tasks:
    - name: Install basic CLI tools
      ansible.builtin.homebrew:
        name:
          - zsh
          - bat
          - fd
          - eza
          - fzf
          - jq
          - miller
          - pandoc
          - lazygit
          - lazydocker
          - gnu-sed
          - helix
    - name: Install UI tools
      ansible.builtin.homebrew_cask:
        name:
          - alacritty
          - docker
          - ngrok
          - intellij-idea
          - postman
          - font-hack-nerd-font
          - sf-symbols
          - 1password
          - 1password-cli
          - raycast
          - shortcat
          - karabiner-elements
          - google-chrome
          - telegram
          - slack
          - zoom
    - name: Homebrew-managed languages & their tools
      ansible.builtin.homebrew:
        name:
          - marksman
          - bash-language-server
          - shellcheck
          - shfmt
          - yaml-language-server
          - yamllint
          - ansible-language-server
          - ansible-lint
          - jdtls
          - google-java-format
          - coursier
          - go
          - node
          - typescript-language-server
          - vscode-langservers-extracted
    - name: Install Coursier-managed tools
      ansible.builtin.shell: |
        cs install metals
        cs install scalafmt
    - name: Install Go-managed tools
      ansible.builtin.shell: |
        go install golang.org/x/tools/gopls@latest
        go install github.com/go-delve/delve/cmd/dlv@latest
        go install mvdan.cc/gofumpt@latest
        go install github.com/nametake/golangci-lint-langserver@latest
        go install github.com/a-h/templ/cmd/templ@latest
    - name: Install Node-managed tools
      ansible.builtin.npm:
        global: true
        name:
          - tailwindcss/language-server
          - olrtg/emmet-language-server
    - name: Check if Rustup is installed
      shell: command -v rustup
      register: rustup_exists
      ignore_errors: yes
    - name: Install Rustup
      ansible.builtin.shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
      when: rustup_exists is failed
    - name: Install Rustup- and Cargo-managed tools
      ansible.builtin.shell: |
        rustup component add rust-analyzer
        rustup component add clippy
        rustup component add rustfmt

        cargo install taplo-cli --locked
        cargo install --git https://github.com/estin/simple-completion-language-server.git
    - name: Check if SDKMan is installed
      shell: command -v sdk
      register: sdkman_exists
      ignore_errors: yes
    - name: Install SDKman
      ansible.builtin.shell: curl -s "https://get.sdkman.io" | bash
      when: sdkman_exists is failed
    - name: Install SDKMan-managed tools
      ansible.builtin.shell: |
        sdk install java
        sdk install scala
