---
- name: Setup my computing environment
  hosts: localhost
  tasks:
    ### Install essential tools
    - name: Install essential CLI tools
      homebrew:
        name:
          - zsh # Ze shell to use
          - powerlevel10k # Better command line prompt
          - bat # Prettier `cat`
          - eza # Better `ls`
          - gnu-sed # GNU implementation of `sed`
          - fzf # Command-line fuzzy finder
          - ripgrep # Search tool like `grep` and `The Silver Searcher`
          - fd # A simple alternative to `find`
          - jq # JSON processor
          - miller # Like sed, awk, cut, join & sort for name-indexed data such as CSV
          - pandoc # Swiss-army knife of markup format conversion
          - lf # Terminal file manager
          - lazygit # Simple terminal UI for `git` commands
          - lazydocker # Simple terminal UI for `docker` commands
          - stow # Essential tools for symlinking configurations
          - hx # A great modern terminal-based modal editor
          - tmux # An unreplaceable terminal emulator
    - name: Install essential UI tools
      homebrew_cask:
        name:
          - font-hack-nerd-font
          - docker
          - alacritty
          - shortcat
          - raycast
          - karabiner-elements
          - google-chrome
          - telegram
    ### Setup git, repositories, directories, and symlinks
    - name: Check public scripts directory doesn't exist
      shell: defaults write -g ApplePressAndHoldEnabled -bool false
    - name: Check public scripts directory doesn't exist
      stat:
        path: ~/public-scripts
      register: public_scripts
    - name: Clone my public scripts
      git:
        repo: git@github.com:pavlo-skobnikov/public-scripts.git
        dest: ~/public-scripts
        accept_hostkey: true
      when: not public_scripts.stat.exists
    - name: Allow execution of public scripts
      file:
        path: ~/public-scripts
        state: directory
        recurse: true
        mode: a+x
    - name: Check private scripts directory doesn't exist
      stat:
        path: ~/private-scripts
      register: private_scripts
    - name: Clone my private scripts
      git:
        repo: git@github.com:pavlo-skobnikov/private-scripts.git
        dest: ~/private-scripts
        accept_hostkey: true
      when: not private_scripts.stat.exists
    - name: Allow execution of private scripts
      file:
        path: ~/private-scripts
        state: directory
        recurse: true
        mode: a+x
    - name: Check secrets directory doesn't exist
      stat:
        path: ~/secrets
      register: secrets
    - name: Clone my secrets
      git:
        repo: git@github.com:pavlo-skobnikov/secrets.git
        dest: ~/secrets
        accept_hostkey: true
      when: not secrets.stat.exists
    - name: Check dotfiles directory doesn't exist
      stat:
        path: ~/dotfiles
      register: dotfiles
    - name: Clone dotfiles
      git:
        repo: git@github.com:pavlo-skobnikov/dotfiles.git
        dest: ~/dotfiles
        accept_hostkey: true
      when: not dotfiles.stat.exists
    - name: Remove temporary .zprofile and stow dotfiles
      shell: |
        rm ~/.zprofile
        ~/public-scripts/stow-dotfiles.sh
    - name: Check projects directory doesn't exist
      stat:
        path: ~/dev/projects
      register: projects
    - name: Create projects directories
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - ~/dev/projects/personal
        - ~/dev/projects/work
      when: not projects.stat.exists
